version: '3.10'
services:
    backend_flask_app:
        container_name: ${TEAM_NAME}_backend_app
        restart: on-failure:5
        build:
                context: ./backend
                dockerfile: Dockerfile
        ports: 
                - 0.0.0.0:${APP_PORT}:5000
        environment:
                - DB_NAME=${TEAM_NAME}_db
        networks:
                flask_network:
                        aliases:
                                - flask-network
        command: flask run --host=0.0.0.0 --port=5000
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1G
                reservations:
                    cpus: '1'
                    memory: 512M
volumes:
        flask_volume:
networks:
        flask_network: